main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: about
    name: About
    url: about
    weight: 2
  - identifier: archive
    name: Archive
    url: archive
    weight: 3
  - identifier: posts
    name: Posts
    url: posts
    weight: 4
  - identifier: Projects
    name: Projects
    url: projects
    weight: 5
