logoText: QJasper
logoType: short
description: Mi casa

backgroundImageLocal: "/images/background/winter-museum.jpg"

custom_js: []
useFaviconGenerator: true
meta_image: ''
themecolor: ''
themeOptions:
  - dark
notAllowedTypesInHome:
  - contact
  - talks
  - about
  - showcase
  - publication
  - presentation
  - resume
notAllowedTypesInHomeSidebar:
  - about
  - archive
  - showcase
  - publication
  - presentation
  - resume
notAllowedTypesInArchive:
  - about
  - talks
  - showcase
  - publication
  - presentation
  - resume
notAllowedTypesInHomeFeed:
  - about
  - archive
  - contact
  - talks
  - showcase
  - publication
  - presentation
  - resume
  - gallery
viewportSize: narrow
enableUiAnimation: false
hideSingleContentsWhenJSDisabled: false
enablePinnedPosts: true
minItemsToShowInTagCloud: 1
enableAppbarSearchIcon: true
enableAppbarLangIcon: false
homeHeaderType: img
hideHomeHeaderWhenMobile: true
showMobileMenuTerms:
  - tags
  - categories
enableBreadcrumb: true
enablePhotoSwipe: true
enableSearch: true
enableSearchHighlight: true
enableGoToTop: true
enableWhoami: true
summaryShape: classic
searchResultPosition: main
archiveGroupByDate: '2006'
archivePaginate: 13
paginateWindow: 1
talksPaginate: 5
talksGroupByDate: '2006'
pubPaginate: 20
writtenTimeIcon: "\U0001F4C5"
modifiedTimeIcon: "\U0001F4DD"
readingTimeIcon: ☕
authorIcon: ✍️
pagePvIcon: "\U0001F440"
pinIcon: "\U0001F4CC"
tagIcon: "\U0001F3F7️"
publicationIcon: "\U0001F4DA"
typeIcon: "\U0001F3AF"
myname: Quinton Jasper
email: 'qjasper [at] proton [dot] me'
whoami: Software Engineer & Aspiring Data Scientist
bioImageUrl: ''
useGravatar: false
organization: Northern Arizona University
enableBio: false
enableBioImage: true
enableSidebar: true
enableSidebarTags: true
enableSidebarSeries: true
enableSidebarCategories: true
enableHomeSidebarTitles: true
enableListSidebarTitles: true
enableToc: true
hideToc: false
tocFolding: true
tocPosition: inner
enableTocSwitch: true
itemsPerCategory: 5
sidebarPosition: left
tocLevels:
  - h1
  - h2
  - h3
  - h4
enableSidebarPostsByOrder: true
showPoweredBy: false
showFeedLinks: true
showSocialLinks: true
enableLangChange: false
enableThemeChange: false
googleTagManager: ''
baiduAnalytics: ''
enableBusuanzi: false
busuanziSiteUV: false
busuanziSitePV: false
busuanziPagePV: false
updatePeriod: weekly
updateFrequency: ''
fullContents: false
enableComment: false
disqus_shortname: ''
commento: false
telegram:
  enable: false
  siteId: ''
  dataLimit: 5
gitment:
  owner: ''
  repo: ''
  clientId: ''
  clientSecret: ''
utterances:
  owner: ''
  repo: ''
gitalk:
  owner: ''
  repo: ''
  clientId: ''
  clientSecret: ''
valine:
  enable: false
  appId: 你的appId
  appKey: 你的appKey
  notify: false
  verify: false
  avatar: mm
  placeholder: 说点什么吧...
  visitor: false
changyan:
  changyanAppid: ''
  changyanAppkey: ''
livere:
  livereUID: ''
isso:
  enable: false
  scriptSrc: ''
  dataAttrs: ''
socialOptions:
  email: ''
  phone: ''
  facebook: ''
  twitter: ''
  github: 'https://github.com/mexiquin'
  stack-overflow: ''
  instagram: ''
  google-plus: ''
  youtube: ''
  medium: ''
  tumblr: ''
  linkedin: ''
  pinterest: ''
  stack-exchange: ''
  telegram: ''
  steam: ''
  weibo: ''
  douban: ''
  csdn: ''
  gitlab: ''
  mastodon: ''
  jianshu: ''
  zhihu: ''
  signal: ''
  whatsapp: ''
  matrix: ''
  xmpp: ''
  dev-to: ''
  gitea: ''
  google-scholar: ''
donationOptions:
  enable: false
  alipay: ''
  wechat: ''
  paypal: ''
  patreon: ''
footerLinks:
  - name: 
    link: 
